import { ROLES } from "./roles";

export const NAV_ITEMS = [
  {
    key: "dashboard",
    label: "Dashboard",
    icon: "LayoutDashboard",
    href: "/dashboard",
    roles: [ROLES.ADMINISTRADOR, ROLES.DIRECTOR, ROLES.CAE, ROLES.ALMACEN],
  },
  {
    key: "proveedores",
    label: "Proveedores",
    icon: "Building2",
    href: "/proveedores",
    roles: [ROLES.ADMINISTRADOR, ROLES.ALMACEN],
  },
  {
    key: "ingresos",
    label: "Ingreso de Productos",
    icon: "PackagePlus",
    href: "/ingresos",
    roles: [ROLES.ADMINISTRADOR, ROLES.ALMACEN],
  },
  {
    key: "stock",
    label: "Inventario",
    icon: "Boxes",
    href: "/stock",
    roles: [ROLES.ADMINISTRADOR, ROLES.DIRECTOR, ROLES.CAE, ROLES.ALMACEN],
  },
  {
    key: "estudiantes",
    label: "Alumnos",
    icon: "Users",
    href: "/estudiantes",
    roles: [ROLES.ADMINISTRADOR, ROLES.CAE],
  },
  {
    key: "qr-scanner",
    label: "Escaneo QR",
    icon: "QrCode",
    href: "/qr-scanner",
    roles: [ROLES.DOCENTE, ROLES.ADMINISTRADOR],
  },
  {
    key: "distribuciones",
    label: "Distribuciones",
    icon: "Utensils",
    href: "/distribuciones",
    roles: [ROLES.ADMINISTRADOR, ROLES.DIRECTOR, ROLES.CAE],
  },
  {
    key: "vehiculos",
    label: "Control Vehicular",
    icon: "Truck",
    href: "/vehiculos",
    roles: [ROLES.OPERARIO_LOGISTICO, ROLES.ADMINISTRADOR],
  },
  {
    key: "reportes",
    label: "Reportes",
    icon: "BarChart3",
    href: "/reportes",
    roles: [ROLES.ADMINISTRADOR, ROLES.DIRECTOR, ROLES.CAE],
  },
  {
    key: "actas",
    label: "Actas de Recepción",
    icon: "FileText",
    href: "/actas",
    roles: [ROLES.ADMINISTRADOR, ROLES.CAE, ROLES.ALMACEN],
  },
  {
    key: "discrepancias",
    label: "Discrepancias",
    icon: "AlertTriangle",
    href: "/discrepancias",
    roles: [ROLES.ADMINISTRADOR, ROLES.DIRECTOR, ROLES.CAE],
  },
  {
    key: "etiquetas",
    label: "Etiquetas QR Lotes",
    icon: "Tag",
    href: "/etiquetas",
    roles: [ROLES.ADMINISTRADOR, ROLES.ALMACEN],
  },
  {
    key: "usuarios",
    label: "Usuarios",
    icon: "UserCog",
    href: "/usuarios",
    roles: [ROLES.ADMINISTRADOR],
  },
];
